import { AdminUser2 } from "@/types/admin";

const users: AdminUser2[] = [
  {
    id: "USR-10002",
    full_name: "John Smith",
    email: "john@example.com",
    balance: 42500,
    otpStatus: "used",
    status: "active",
    joined: "Aug 29, 2026",
  },
  {
    id: "USR-10003",
    full_name: "David James",
    email: "david@example.com",
    balance: 8200,
    otpStatus: "pending",
    status: "suspended",
    joined: "Aug 27, 2026",
  },
  {
    id: "USR-10004",
    full_name: "Sarah Adams",
    email: "sarah@example.com",
    balance: 125000,
    otpStatus: "used",
    status: "active",
    joined: "Aug 25, 2026",
  },
  {
    id: "USR-10005",
    full_name: "Michael Brown",
    email: "michael@example.com",
    balance: 15000,
    otpStatus: "Not Set",
    status: "suspended",
    joined: "Aug 23, 2026",
  },
  {
    id: "USR-10006",
    full_name: "Daniel Williams",
    email: "daniel@example.com",
    balance: 68500,
    otpStatus: "used",
    status: "active",
    joined: "Aug 20, 2026",
  },
  {
    id: "USR-10007",
    full_name: "Grace Johnson",
    email: "grace@example.com",
    balance: 9300,
    otpStatus: "pending",
    status: "deleted",
    joined: "Aug 18, 2026",
  },
  {
    id: "USR-10008",
    full_name: "Samuel Wilson",
    email: "samuel@example.com",
    balance: 47200,
    otpStatus: "used",
    status: "active",
    joined: "Aug 15, 2026",
  },
];
